run_name: "WikiText"
silent: true
project: "TabulaPrima"
entity: "jordan-ledoux-none"
tags: ["experiment", "generic-dataset", "pretraining"]
log: true
use_time_based_instrument: true
instruments_per_second: 5
save_checkpoints: false
save_final_model: false