# Default selections for different configuration groups
defaults:
  - config_schema
  - _self_
  - model: 278m_params_large_context
  - training: 4090_base
  - dataset: fineweb_10bt
  - tokenizer: tiktoken

# Parameters that don't fit neatly into other groups (like args in train.py)
use_live_display: true
use_stats: true
float_32_precision: highest

# Define where Hydra should store outputs (logs, saved configs, checkpoints if not overridden)
# Hydra automatically creates dated/timed subdirectories here
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true