# Default selections for different configuration groups
defaults:
  - config_schema
  - _self_
  - model: 278m_params
  - training: 278m_params
  - dataset: wikitext
  - tokenizer: tiktoken
  - console: with_live

float_32_precision: highest

# Define where Hydra should store outputs (logs, saved configs, checkpoints if not overridden)
# Hydra automatically creates dated/timed subdirectories here
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true