# @package _global_
defaults:
  - override /dataset: fineweb_10bt
  - override /tokenizer: tiktoken
  - override /console: with_live
  - override /model: 278m_params 
  - override /training: 278m_params
  - _self_

# Parameters that don't fit neatly into other groups (like args in train.py)
float_32_precision: highest

model:
  max_seq_len: 1024
training:
  batch_size: 4
  grad_steps: 8
  eval_interval: 500

# Define where Hydra should store outputs (logs, saved configs, checkpoints if not overridden)
# Hydra automatically creates dated/timed subdirectories here
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true